-- Create the plans table first as users will reference it
CREATE TABLE plans (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(255) NOT NULL UNIQUE,
                       requests_per_month INT NOT NULL,
                       requests_per_day INT NOT NULL
);

-- Create the collection table for plan price IDs
CREATE TABLE plan_stripe_prices (
                                    plan_id BIGINT NOT NULL,
                                    stripe_price_id VARCHAR(255) NOT NULL,
                                    PRIMARY KEY (plan_id, stripe_price_id),
                                    FOREIGN KEY (plan_id) REFERENCES plans(id) ON DELETE CASCADE
);

-- Create the users table
CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       email VARCHAR(255) NOT NULL UNIQUE,
                       password VARCHAR(255) NOT NULL,
                       enabled BOOLEAN NOT NULL,
                       verification_code VARCHAR(255),
                       verification_expiration TIMESTAMP,
                       notion_access_token VARCHAR(1024),
                       notion_workspace_id VARCHAR(255),
                       notion_bot_id VARCHAR(255),
                       notion_target_database_id VARCHAR(255),
                       notion_target_database_name VARCHAR(255),
                       notion_workspace_name VARCHAR(255),
                       notion_workspace_icon VARCHAR(255),
                       created_at TIMESTAMP NOT NULL,
                       updated_at TIMESTAMP NOT NULL,
                       plan_id BIGINT,
                       requests_in_current_month INT,
                       plan_refresh_date DATE,
                       requests_in_current_day INT,
                       FOREIGN KEY (plan_id) REFERENCES plans(id)
);

-- Create the taskLists table
CREATE TABLE taskLists (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       title VARCHAR(255),
                       description TEXT,
                       created_at TIMESTAMP,
                       updated_at TIMESTAMP,
                       user_id BIGINT,
                       FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Create the collection table for taskList items
CREATE TABLE task_items (
                            task_id BIGINT NOT NULL,
                            item VARCHAR(1024),
                            FOREIGN KEY (task_id) REFERENCES taskLists(id) ON DELETE CASCADE
);