-- C:/Users/irela/Programming/Java/task-pilot-backend/src/main/resources/db/migration/V2__tasklist_and_todos.sql

-- Rename tasklists to task_lists
-- The original table was created as 'tasklists' (lowercase) because it was unquoted in V1.
ALTER TABLE tasklists RENAME TO task_lists;

-- Create new 'todos' table
CREATE TABLE todos (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       content VARCHAR(1000) NOT NULL,
                       checked BOOLEAN NOT NULL DEFAULT FALSE,
                       deadline TIMESTAMP NULL,
                       task_list_id BIGINT NOT NULL,
                       CONSTRAINT fk_todos_task_list
                           FOREIGN KEY (task_list_id)
                               REFERENCES task_lists (id)
                               ON DELETE CASCADE
);

CREATE INDEX idx_todos_task_list_id ON todos (task_list_id);

-- Migrate data from 'task_items' (ElementCollection) to 'todos'
-- Map 'item' -> 'content', default checked=false, deadline=NULL
-- Note: The foreign key in task_items was task_id, which we map to task_list_id
INSERT INTO todos (content, checked, deadline, task_list_id)
SELECT ti.item, FALSE, NULL, ti.task_id
FROM task_items ti;

-- Drop old collection table
DROP TABLE task_items;